version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - commerceai-network

  # Cache Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - commerceai-network

  # Frontend Test (pour commencer)
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - commerceai-network

# Volumes persistants
volumes:
  mongodb_data:
  redis_data:

# Réseau interne
networks:
  commerceai-network:
    driver: bridge
