global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'commerceai-pro'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node.js application metrics
  - job_name: 'nodejs-apps'
    static_configs:
      - targets: 
        - 'api-gateway:4000'
        - 'agent-customer-service:5001'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # System metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application health checks
  - job_name: 'health-checks'
    static_configs:
      - targets:
        - 'api-gateway:4000'
        - 'agent-customer-service:5001'
        - 'agent-analysis:5002'
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 5s
    honor_labels: true

  # AI Agent specific metrics
  - job_name: 'ai-agents'
    static_configs:
      - targets:
        - 'agent-customer-service:5001'
        - 'agent-analysis:5002'
        - 'agent-content-generation:5003'
        - 'agent-advertising:5004'
        - 'agent-email-marketing:5005'
        - 'agent-page-generation:5006'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Security monitoring
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['api-gateway:4000']
    scrape_interval: 10s
    metrics_path: /security-metrics
    scrape_timeout: 5s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"